project:
  type: website
  output-dir: docs

website:
  title: "Econ4261"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Lectures/Lecture-3-LinearModels.qmd
        textL Lecture 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



