project:
  type: website
  output-dir: docs

website:
  title: "Econ4261"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Lectures.qmd
      - Recitations.qmd
      - Data.qmd
      - text: "Homework"
        menu:
          - assignments/GroupProject.qmd
          - assignments/Homework-1.qmd
          - assignments/Homework-2.qmd 
          - assignments/Homework-3.qmd
          - assignments/Homework-4.qmd
          - assignments/Homework-5.qmd
      - Exercises.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



