project:
  type: website
  output-dir: docs

website:
  title: "Econ4261"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Lectures.qmd
      - assignments/GroupProject.qmd
      - Recitations.qmd
      - Data.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



