---
title: "Lecture Slides"
---

Materials here will be uploaded as we continue through the course.

| Topic | Slides | 
| ----- | ------ |
| Introduction and Syllabus | [Slides](lectures/Intro-SyllabusOverview.qmd) |
| Introduction: Overview of Applications | [Slides](lectures/Intro-1-Applications.qmd) |
| Review: Probability and Statistics | [Slides](lectures/Intro-2-ProbabilityStats.qmd) |
| Review: Linear Models | [Slides](lectures/Intro-3-LinearModels.qmd) |
| Causality | [Slides](lectures/Causality.qmd) |
| Experiments in Economics | [Slides](lectures/Experiments-Application.qmd) |
| Introduction to Difference in Differences | [Slides](lectures/Diff-in-Diff-Intro.qmd) | 
| A Regression Framework for Diff-in-Diff | [Slides](lectures/Diff-in-Diff-Regression.qmd) |
| Application: the Child Penalty | [Slides](lectures/Diff-in-Diff-ChildPenalty.pdf) |
| Application: Neighborhood Effects and Moving to Opportunity | [Slides](lectures/movers_paper1_slides.pdf) |
| Instrumental Variables | [Slides](lectures/IV-Intro.qmd) |
| Regression Discontinuity | |
| Teaching Evals | [Slides](lectures/TeachingEvalutions.qmd) |