---
title: "Group Project"
---

## Project Description

In groups of 5 to 6, you will use the tools we have learned in this course to conduct a quantitative analysis on a topic of your choice. This analysis may be your own original work, or a replication of a paper.

Although you will work together to conduct the analysis, you will **write and submit your own individual reports**. The report (3-5 pages including references, figures, and tables) will have the following structure:

1. Introduction
   1. What is the empirical question you are attempting to answer?
   2. Describe why (using citations when necessary) this question is of interest. If possible, describe the economic theory underlying your question and how your analysis will help quantify it.
   3. Provide a brief literature review (a cogent summary of 2-3 papers that highlights the key points) on this topic.
   4. Specify the method of analysis you are going to use (linear regression, instrumental variables, difference in differences, etc). If you are replicating a paper, specify which paper.
2. Data
   1. Describe how the data you are using for your analysis is constructed, including any sample selection criteria.
   2. Provide a descriptive analysis of the data, including an analysis of the relationship between your outcome variable of interest and the causal variable of interest in your question.
3. Main Analysis
   1. Explain why the cross-sectional relationship that you demonstrated in section (2) may not recover a causal relationship.
   2. Describe the method you are going to use to answer your question and **clearly** articulate the assumptions under which this method correctly estimates a causal relationship between the two variables.
   3. Present the analysis and discuss results.

## Project Timeline

| Week | Deadline |
| ------ | -------- |
| Week 3 | Teams are formed and groups discuss topics |
| Week 4 | Meeting 1 with WA: teams discuss topic with WA | 
| Week 5 | Meeting 2: teams find 2-3 relevant papers on the topic |
| Week 6 | Meeting 3: teams establish data source |
| Week 7 | Teams finalize research question, data source, and related papers |
|        | Spring Break
| Week 8 | Teams work on descriptive analysis |
| Week 9 | Meeting 4: teams meet with WA to get feedback on descriptive analysis |
| Week 10 | Teams work on descriptive analysis and main (causal) analysis |
| Week 11 | Teams work on main (causal) analysis |
| Week 12 | Meeting 5: teams meet with WA to get feedback on main analysis |
| Week 13 | |
| Week 13 | |
| Week 14 | |


## Rules for Submission

1. Written reports that are identical will not be graded.
2. There is no advantage in grading for original work vs a replication, but in both cases you will be assessed on your ability to use tools critically and independently. There is scope for providing original analysis and insight in the replication study also. 
3. Students must submit **both** their written report as well as the code they used to generate the results in their report. Students in the same group are allowed to submit the same code if their results are identical.

## Suggested List of Topics

If you are struggling to come up with questions for your research project, here is a suggested list of topics.



## Finding Data and Replication Materials

Most journals in economics require authors to provide replication materials, including data (when these sources are not confidential). Some journals in which you may find interesting empirical topics from the last ten years include the American Economic Review (plus the associated journals of AER:Macro, AER:Micro, AER:Applied, and AER:Policy), Econometrica, the Quarterly Journal of Economics, the Journal of Political Economy, the Review of Economic Studies, the Journal of Labor Economics, the Journal of Public Economics, and Economic Journal. The websites for these journals host all replication materials. 

## ECON Capstone-level writing criteria

1. Concisely summarizes the essential information about the project.
2. Applies a standard economics paper layout with an introduction (includes research question and thesis), discussion, data, model, and regressions to test the model, results, and conclusion sections as appropriate to the setting.
3. Explain the connection between the hypothesis and the chosen model, explain what proof would confirm or disprove the hypothesis, and justify the use of the selected model.
4. Identifies appropriate data from reputable sources; uses an appropriate sample size; and cites all sources used.
5. Develops a brief literature review that demonstrates an understanding of the relevance of the proposed hypothesis and its relationship to current knowledge.
6. Uses mathematical equations or technical language accurately to explain models and effects.
7. States and interprets all results of regressions and explains clearly how the results confirm or disprove the hypothesis/model. 
8. When presenting empirical research, explains equations and the intuition behind the choice of independent and dependent variables.
9. Uses appropriate formatting (graphs and tables are labeled accurately) and language conventions (e.g. no spelling or grammatical errors).